name: "🚀 publish npm package"

on:
    push:
        branches:
          - master 

jobs:
    release:
        name: 🚀 publish npm package
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: action/checkout@v2.1.1
            - name: node
              uses: actions/setup-node@v1.4.2
              with:
                  node-version: 12
                  registery-url: https://registery.npmjs.org
            - name: 🚀 publish
              run: npm publish --access public
              env: 
                  NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}